spring:
  application:
    name: incident-service

  datasource:
    url: jdbc:mysql://localhost:3306/resq_incidentdb
    username: resq_user
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082